### ISSUE TITLE
mesa store path is haunted

### ISSUE THREAD

**Issue by yu-re-ka** [tpwrules/nixos-apple-silicon#199]
Now the third person describing an issue where after a rebuild, graphics acceleration does not work. After debugging it turns out the mesa driver has some regions zeroed out.

This was originally reported in the Lix issue tracker since the first two known cases were with Lix, however a third case has appeared which was running CppNix.

A hypothesis is that high load/contention on the builder would increase the likelihood of this issue manifesting. When rebuilding an equivalent mesa derivation afterwards it always turned out fine. nixos-apple-silicon users will usually build the kernel and mesa at the same time. Currently the fault has not been isolated. It could be in the kernel, in the toolchain, in the mesa build system...

https://git.lix.systems/lix-project/lix/issues/248

**Comment by tpwrules** [comment]
Here are two more manifestations with CppNix (not 100% sure which version) from a bit ago: https://github.com/tpwrules/nixos-apple-silicon/issues/156 (along with one corrupted file)

Is the bad region similar? I try to bang on Mesa a little bit after each release but have not managed to personally replicate the problem on my 64GB M1 Max with ext4. I have had one or two non-deterministic builds but haven't captured a good and a bad build to compare because I didn't realize the necessity at the time.

Help tracking/correlating this would be greatly appreciated. I don't think I've heard of it happening with Mesas labeled as 23, but it has evidently persisted across a couple Asahi patch releases.

**Comment by lf-** [comment]
fyi our one bad copy has the zeroed region aligned with a section header, if that's helpful. you can throw yours in ghidra and check if it's the same, perhaps?

**Comment by flokli** [comment]
I was hoping someone is gonna do the correlation with the other data for me 😄 not sure I'll get to debug this too much more in the next few days.

**Comment by puckipedia** [comment]
fwiw, 00590000 through 00682000 are zeroed, and `loader_bind_extensions` is right in the middle of that.

**Comment by alyssais** [comment]
I think I'm having this same problem on my musl system.  In that case, Weston just segfaults — presumably musl's dynamic linker is less resilient than this than glibc?

Working mesa:

```
Dynamic section at offset 0x1a993b8 contains 43 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libglapi.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libdrm.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libLLVM-17.so]
 0x0000000000000001 (NEEDED)             Shared library: [libexpat.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libz.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libzstd.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libxcb-dri3.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libsensors.so.5]
 0x0000000000000001 (NEEDED)             Shared library: [libdrm_radeon.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libelf.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libdrm_amdgpu.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libdrm_nouveau.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so]
 0x000000000000000e (SONAME)             Library soname: [libgallium_dri.so]
 0x000000000000001d (RUNPATH)            Library runpath: [/nix/store/1y3ylzq54isc3gv3c9z3wzmsn9zhkava-mesa-24.0.5/lib:/nix/store/zj2ngf5vys1q1vighya96509pq2x61id-llvm-17.0.6-lib/lib:/nix/store/sa9hg23bpay7hcj4356hp89k292g70pv-expat-2.6.2/lib:/nix/store/yp1yccxyw8vybxly9ilnc4jivg694p5x-zlib-1.3.1/lib:/nix/store/qnni1gp9lw0gkk3ayx4jcgphk9jgzr12-libxcb-1.16/lib:/nix/store/pkvyh5s1yh1p6qygzm8vkriyx5xf549q-zstd-1.5.6/lib:/nix/store/gaar581489n42j30dgc7bfncd32swq4p-lm-sensors-3.6.0/lib:/nix/store/v3g582x5c85xipldx4r2d1qfyyv54ahs-elfutils-0.191/lib:/nix/store/kwfvy4wankdca4x1cfk96w3671mkx6cl-libdrm-2.4.120/lib:/nix/store/98jcl1340c5jhxd3qw6014b12ij7395v-musl-1.2.3/lib:/nix/store/8kyc73l5j7y2k7b47ls3lzpx86i4z93c-gcc-13.2.0-lib/lib:/nix/store/y7njb653ncgil58wgwk6brj28f7q6y6v-mesa-24.0.5-drivers/lib:/nix/store/z3d3vy8ssi8790xsk7awfqigmnv8idgr-vulkan-loader-1.3.280.0/lib]
 0x000000000000000c (INIT)               0xf0d20
 0x000000000000000d (FINI)               0x118b454
 0x0000000000000019 (INIT_ARRAY)         0x19c8d98
 0x000000000000001b (INIT_ARRAYSZ)       320 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x19c8ed8
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x0000000000000004 (HASH)               0x1cb5488
 0x000000006ffffef5 (GNU_HASH)           0x17b8
 0x0000000000000005 (STRTAB)             0x1cc0000
 0x0000000000000006 (SYMTAB)             0x1978
 0x000000000000000a (STRSZ)              22448 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x1a996a8
 0x0000000000000002 (PLTRELSZ)           18384 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0xec550
 0x0000000000000007 (RELA)               0xc2a0
 0x0000000000000008 (RELASZ)             918192 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000000000001e (FLAGS)              BIND_NOW
 0x000000006ffffffb (FLAGS_1)            Flags: NOW
 0x000000006ffffffe (VERNEED)            0xc220
 0x000000006fffffff (VERNEEDNUM)         3
 0x000000006ffffff0 (VERSYM)             0xbb6a
 0x000000006ffffff9 (RELACOUNT)          37790
 0x0000000000000000 (NULL)               0x0
```

Bad mesa:

```
Dynamic section at offset 0x1d30000 contains 2 entries:
  Tag        Type                         Name/Value
 0x000000000000001d (RUNPATH)            Library runpath: [:/nix/store/fl1wirq9vp7jh985jqfj7bn9ynss49vk-mesa-24.0.5-drivers/lib:/nix/store/cl0mgj27variyndyij4f2jf1fp7jhxx9-vulkan-loader-1.3.280.0/lib]
 0x0000000000000000 (NULL)               0x0
```

**Comment by lf-** [comment]
hi @marcan, this may interest you by this point, given we have multiple people hitting it.

**Comment by tpwrules** [comment]
@alyssais Just to be clear, the VM system is running on a machine which uses NixOS on Apple Silicon, but with a custom kernel? Are you building the Asahi Mesa or the standard nixpkgs one? The VM uses the standard NixOS kernel?

**Comment by alyssais** [comment]
VM uses the standard NixOS kernel with some config modifications, and standard mesa.  Asahi mesa is not involved in the system at all — I just use simpledrm on the host.

**Comment by lf-** [comment]
puck thinks this might be a patchelf bug which would explain it only hitting mesa and on NixOS.

**Comment by puckipedia** [comment]
so, my current working theory is that this is not patchelf, but a repeat of a previous issue; tho i'm not entirely sure why it doesn't affect x86_64, as it should have the same bug.

Since NixOS/nixpkgs#207101, `strip` is parallelised. This already turned out to be a problem, as `strip` running multiple processes simultaneously on the same file has caused issues on aarch64 before; see NixOS/nixpkgs#246147. As I was trying to debug this, I built the same store path on a Hetzner aarch64 VPS, as well as locally using qemu-user. What I noticed was that the `strtab` of the natively-built mesa's `dri` was a size `8`, rather than a size `0x165199` when built under qemu-user. The rest of the ELF was identical. After a bit more digging, it turns out that mesa's `dri` driver is hard-linked to every single `{foo}_dri.so` path. This is eventually deduplicated, but this is done _after_ running strip. Which means that, in effect, it was running strip over the same file, once again, repeating issue 246147. In my case, this showed up as the `strtab` being truncated, but I could imagine this showing up differently for other people (e.g. a part of a section missing, but _always_ section-aligned, because that's how it's written by binutils).

I believe that moving the symlink deduping logic from `postFixup` to `preFixup` is likely to solve this issue; but as I don't have a real aarch64 device to test with, I leave the implementation of this suggestion to others :)

**Comment by puckipedia** [comment]
I've been pointed at https://github.com/void-linux/void-packages/blob/master/srcpkgs/mesa/patches/megadriver-symlinks.patch - which is likely to be a better solution here; just patching the megadriver installer to symlink, rather than hardlink.

**Comment by alyssais** [comment]
It looks like Mesa uses hard links for a reason — [to avoid installing the megadriver under its original non-driver-specific name](https://gitlab.freedesktop.org/mesa/mesa/-/blob/3218056e0eb375eeda470058d06add1532acd6d4/src/gallium/targets/dri/Makefile.am#L135-136), and I think it makes sense not to change that, so based on my current understanding I'd prefer moving our symlinkification to preFixup rather than applying Void's patch.

@dcbaker do you have any thoughts here, ooc?

**Comment by minego** [comment]
While we're waiting for agreement on how to proceed to fix this, does anyone have instructions on how someone can work around this if they run into it?

I believe I ran into this last night, and my nix-fu is not strong enough to know how to force rebuliding mesa... (but I'm eager to learn!)

**Comment by lf-** [comment]
> While we're waiting for agreement on how to proceed to fix this, does anyone have instructions on how someone can work around this if they run into it?
> 
> I believe I ran into this last night, and my nix-fu is not strong enough to know how to force rebuliding mesa... (but I'm eager to learn!)

I think the fix here is to do something (this is evil btw) like:

```
nix path-info --derivation /nix/store/gsdfkhlsdfglhk-mesa
(prints some derivation path)
nix store delete --ignore-liveness STORE-PATH-DRV
nix build STORE-PATH-DRV
```

**Comment by minego** [comment]
Wish I'd tried that approach first lol

I was attempting a few things with that flag and, totally borked my install! Luckily booting a rescue image is easy with NixOS and it is fixed now. I wiped my whole nix store and started fresh, and mesa built properly this time.

On Thu, May 23, 2024, at 6:08 PM, Yureka wrote:
> 
> 
> I can not recommend doing anything with `--ignore-liveness`, it is too easy to fuck up your entire system with that.
> 
> Instead, I suggest adding an overlay that makes a meaningless change to the derivation (but changes the derivation hash):
> 
> `nixpkgs.overlays = [
>   (final: prev: {
>     mesa-asahi-edge = prev.mesa-asahi-edge.overrideAttrs (oldAttrs: {
>       src = lib.cleanSource oldAttrs.src;
>     });
>   })
> ];
`

**Comment by tpwrules** [comment]
Has an upstream nixpkgs fix to rearrange the mesa derivation been filed?

Can the strip hook be taught to ignore symlinks and only access unique inodes?

**Comment by tpwrules** [comment]
Some late night bash(1)ing to solve the latter: https://github.com/NixOS/nixpkgs/pull/314175

Will actually test over the weekend that it works with nixpkgs; I still haven't managed to replicate the haunting on my machine.

**Comment by alyssais** [comment]
> Has an upstream nixpkgs fix to rearrange the mesa derivation been filed?

I'd been hoping to hear something from Mesa, but failing that, I'll send puck's original suggested fix (moving symlink deduplication to preFixup) in the next few days

**Comment by lheckemann** [comment]
@lf- `nix-store --repair-path` is the more "canonical" way to do that, I believe?

**Comment by tpwrules** [comment]
A fix for the underlying issue has been merged into nixpkgs and will take a week or two to make it to a release here. I am encouraged to wait for that instead of attempting to modify our Mesa build as the rate of occurrence does not seem too high.

I will keep track and close this issue once that release happens. Thanks very much to all again for debugging.

**Comment by lheckemann** [comment]
Huh, I could have sworn it remade the path unconditionally, but apparently not. Sorry for the noise.

**Comment by skylarmb** [comment]
I was having this issue on a fresh install with the latest ISO. I tried the older 4-20-24 release and all is well (at least after configuring `hardware.asahi` and `hardware.opengl`). Looking forward to hearing an update on this issue.

**Comment by flokli** [comment]
The fixes have been merged to nixpks, but it'll take a while to land. Check https://nixpk.gs/pr-tracker.html?pr=314175 and https://nixpk.gs/pr-tracker.html?pr=314541 for when the fix ends up in the unstable and 24.05 channels respectively.

**Comment by zvolin** [comment]
unstable is there already

**Comment by tpwrules** [comment]
This fix is in unstable and also the latest release. Stable will be another week or two, but I'm considering this fixed.

**Comment by dcbaker** [comment]
@alyssais sorry for missing this, I was on a github hiatus. The hardlinks are basically about space savings, and there was this thought that back in the day that a distro might want to update a single driver if that meant that they wouldn't have to update the entire mesa package (something that in reality only Debian could do).

**Comment by alyssais** [comment]
@dcbaker so is there any reason for them not to be symlinks to a megadriver.so?
