### ISSUE TITLE
Can no longer enable GPU

### ISSUE THREAD

**Issue by 347Online** [tpwrules/nixos-apple-silicon#214]
I recently started receiving this mysterious error when the enable gpu setting is true (screenshot captured in cpu rendering mode)

![image](https://github.com/user-attachments/assets/c4133637-630d-4fd4-a8fe-6b39b57ef8da)

I've been banging my head against the wall to no avail. I expect this is due to SOMETHING I did, but I have not been able to trace it back.

This originally manifested under Hyprland, but is still happening under Sway or TTY only. I originally thought a Hyprland thing was to blame but that seems to have proven to be a distraction.

My system is an M1 Pro 16in MacBook Pro if that means anything.

Any assistance would be greatly appreciated, thank you

**Comment by BagMan9** [comment]
Can also confirm, this is happening for me as well.

I have no idea why, but revision f45b8504aeda047fdf6cd803e4fb5fb25f199aa0 of nixpkgs seems to allow it to work. If you use flakes, set your nixpkgs url "github:nixos/nixpkgs/f45b8504aeda047fdf6cd803e4fb5fb25f199aa0". That rev is the only one I've found that works right now - the ones immediately before & after it do not seem to work, which is even stranger.

I'll edit this post with the full trace.

**Comment by rowanG077** [comment]
Isn't it just this: https://github.com/tpwrules/nixos-apple-silicon/pull/213

**Comment by 347Online** [comment]
@rowanG077 Yeah, that looks right to me, based on my failed attempts at debugging this

@BagMan9 I'll try this and report back

**Comment by BagMan9** [comment]
@347Online I went ahead and forked nixpkgs & applied the patch from the upstream PR to it so that I can have the latest updates as the nixpkgs PR was was pretty out of date. If you we're running nixos-unstable for your nixpkgs, you can just replace it with "github:BagMan9/nixpkgs." I'll keep it in sync with nixos-master until the [nixpkgs PR](https://github.com/NixOS/nixpkgs/pull/325449) is merged.

Additionally, the apple-silicon-support repo can be replaced with "github:bkchr/nixos-m1/bkchr-mesa-fix." Just finished rebuilding & am now fully up-to-date with those inputs.

**Comment by tpwrules** [comment]
Fixed in the latest release.
