### ISSUE TITLE
Update asahi-fwextract

### ISSUE THREAD

**Issue by zzywysm** [tpwrules/nixos-apple-silicon#39]
There have been multiple releases of asahi-fwextract since the 0.5pre2 version you currently use.  Assuming the newer versions are not incompatible, it's probably time to switch to the latest (and double-check your patch still applies cleanly).

**Comment by tpwrules** [comment]
To be honest I did kind of forget about that package. I looked and while there have been many additional releases of that installer repo, the only one that actually touched the asahi-fwextract code since the version here is... the upstreaming of my patch. So there is no need to do anything now and the official PKGBUILDs have not changed the version either.

I'll keep this open as a reminder to check it.
