### ISSUE TITLE
Audio/headphones support

### ISSUE THREAD

**Issue by shaunsingh** [tpwrules/nixos-apple-silicon#54]
Hi, I'd love to get audio and headphones working on nixos-apple-silicon, but I'm not quite sure how. From what I understand it should be a matter of adding the asahi ucm configuration to the alsa-ucm-conf package but it still doesn't quite work

Heres my current attempt with an overlay in my config, where `inputs.asahi-alsa-src` points to [asahi's configuration(https://github.com/AsahiLinux/alsa-ucm-conf-asahi)
```nix
alsa-ucm-conf = prev.alsa-ucm-conf.overrideAttrs (old: rec {
  installPhase = ''
    runHook preInstall
    mkdir -p $out/share/alsa
    cp -r ucm ucm2 $out/share/alsa
    cp -r ${inputs.asahi-alsa-src}/ucm2/conf.d/macaudio $out/share/alsa/ucm2/conf.d/macaudio
    runHook postInstall
  '';
});

```

**Comment by yusefnapora** [comment]
I have headphones working on my 14" M1 Pro, but it took me a minute to figure that out, since the DAC volume for the headphone jack was set to zero. This is independent of the pipewire / pulseaudio volume, so it wasn't really obvious what was wrong.

What works for me is to use `alsamixer` or `amixer` from the `alsa-utils` package and set the "Jack DAC" volume. With `alsamixer`, you need to press `F6` and select the audio device (device name should start with "MacBook"), then use the arrow keys to select the "Jack DAC" slider and increase it.

Mine resets to zero on reboot, so I run `${pkgs.alsa-utils}/bin/amixer -c 1 set 'Jack DAC' 100%` in a startup hook for my window manager. The `-c 1` chooses the "card number", which shows up in `alsamixer` when switching devices with F6. On mine, the `default:0` card is a loopback device, and `default:1` is my actual hardware, so that's why I'm using `-c 1`. You might not have a loopback device; mine showed up randomly a little while ago for reasons unknown (maybe wireplumber?).

**Comment by shaunsingh** [comment]
![20230225_11h24m56s_grim](https://user-images.githubusercontent.com/71196912/221368045-d79fd0ee-6708-4f9e-b64e-0a3fc3501631.png)

For me the macbook audio device doesn't show up at all, running a macbook pro M1 13 inch.

**Comment by shaunsingh** [comment]
Finally got it working with the following: 

First make an overlay of `alsa-utils` that adds the proper configurations to alsa 
```nix
asahi-alsa-utils = prev.alsa-utils.override {
  alsa-lib = prev.alsa-lib.override {
    alsa-ucm-conf = prev.alsa-ucm-conf.overrideAttrs (_: {
      installPhase = ''
        runHook preInstall
        mkdir -p $out/share/alsa
        cp -r ucm ucm2 $out/share/alsa
        cp -r ${asahi-alsa-src}/ucm2/conf.d/macaudio $out/share/alsa/ucm2/conf.d/macaudio
        runHook postInstall
      '';
    });
  };
};
```

I found that my audio device for the macbook is #0 (hence `-c 0`) and that instead of `Jack DAC` its named `Jack Mixer`. Running the following sets the volume for me (the `startup` is from the sway home-manager module, I imagine you could use a systemd service to do the same thing)
```nix
startup = [
  {command = "${pkgs.asahi-alsa-utils}/bin/amixer -c 0 set 'Jack Mixer' 100%";}
];
```

**Comment by yusefnapora** [comment]
Awesome!

**Comment by shaunsingh** [comment]
the above fix has mysteriously stopped working for me and I have absolutely no idea why

**Comment by venikx** [comment]
> ![20230225_11h24m56s_grim](https://user-images.githubusercontent.com/71196912/221368045-d79fd0ee-6708-4f9e-b64e-0a3fc3501631.png)
> 
> For me the macbook audio device doesn't show up at all, running a macbook pro M1 13 inch.

Does this still happen? I have the same specs as you, but I seem to receive devices (I installed the 24/06/2023 version.

**Comment by shaunsingh** [comment]
I stopped using Asahi a few months back, but it worked sometimes and didn't work other times

**Comment by tpwrules** [comment]
I'm not sure what the DAC volume issues are about, I didn't need to change that but it seems sometimes that the system volume is louder than other times. Anyway, audio support will be available in the next release.
