### ISSUE TITLE
rust related errors building installer

### ISSUE THREAD

**Issue by whiteley** [tpwrules/nixos-apple-silicon#88]
Using the steps in https://github.com/tpwrules/nixos-apple-silicon/blob/main/docs/uefi-standalone.md#software-preparation I get no errors building `m1n1` or `uboot-asahi` but when I get to `installer-bootstrap` I see many errors like the following

```
linux-aarch64-unknown-linux-gnu> /nix/store/51sszqz1d9kpx480scb1vllc00kxlx79-bash-5.2-p15/bin/bash: line 1: rustc: command not found
linux-aarch64-unknown-linux-gnu> expr: syntax error: unexpected argument '1.69.0'
```

after this the build "succeeds" and an `.iso` is produced but I'm suspicious about its correctness. Are these errors new from upstream changes? Existing and expected?

Thank you!

**Comment by tpwrules** [comment]
I assume this is just the kernel checking for Rust support and giving errors because it is indeed not available in the installer. There's no reason the `.iso` you built shouldn't work if it was indeed produced.

You are also free to download the `.iso` from GitHub to save time. It should be (but isn't always sadly) bit-identical if you build from the same tag on a local x86_64-linux machine.
